import { highlightServerCode } from '@/lib/opendocs/utils/code-theme'
import type { NpmCommands } from '@/lib/opendocs/types/unist'
import { cn } from '@/lib/utils'

import {
  CopyButton,
  CopyNpmCommandButton,
} from './docs/mdx-components/copy-button'

export const InstallationBox = async ({
  theme,
  className,
  __src__,
  __style__,
  __withMeta__,
  __rawString__,
  __bunCommand__,
  __npmCommand__,
  __yarnCommand__,
  __pnpmCommand__,
  ...props
}: React.HTMLAttributes<HTMLPreElement> & {
  __src__?: string
  __rawString__?: string
  __withMeta__?: boolean
  __style__?: 'default' | 'new-york'
  theme?: Parameters<typeof highlightServerCode>[1]
} & NpmCommands) => {
  const htmlCode = await highlightServerCode(
    __rawString__ || '',
    theme || 'Aura Theme',
    'shell'
  )

  return (
    <div className="relative">
      <pre
        className={cn(
          'mb-4 mt-6 max-h-162.5 overflow-x-auto rounded-lg border bg-zinc-950 py-4 text-white dark:bg-zinc-900',
          className
        )}
        {...props}
        // biome-ignore lint/security/noDangerouslySetInnerHtml: Safe - htmlCode is generated by syntax highlighter from trusted source code
        dangerouslySetInnerHTML={{ __html: htmlCode }}
      />

      {__rawString__ && !__npmCommand__ && (
        <CopyButton
          className={cn('absolute right-4 top-10')}
          src={__src__}
          value={__rawString__}
        />
      )}
      {__npmCommand__ &&
        __yarnCommand__ &&
        __pnpmCommand__ &&
        __bunCommand__ && (
          <CopyNpmCommandButton
            className={cn('absolute right-4 top-10')}
            commands={{
              __bunCommand__,
              __npmCommand__,
              __yarnCommand__,
              __pnpmCommand__,
            }}
          />
        )}
    </div>
  )
}
